name: CI

on:
  workflow_dispatch: # Allow running on-demand
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yaml
      - src/**
      - tests/**
      - '!**.md'

jobs:
  build-and-test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
          cache: pip
          cache-dependency-path: requirements*.txt

      - name: Install dependencies
        run: |
          sudo apt-get update
          pip install -r requirements.txt
          pip install -e .

      - name: Unit Tests
        run: |
          pip install pytest pytest-cov
          pytest --cov=src --cov-report=term-missing:skip-covered --cov-fail-under=70 -v tests/
